Repository GoogleCloudPlatform/compute-image-packages, pull requests merged in 2019-07, with the labels that each got.

#799 Disk expand: Make sure the disk has settled before continuing.
  packages/gce-disk-expand/src/expandfs-lib.sh
Labels: cla: yes, size/XS

#800 Allow OS login sudoers change GID too, not only UID
  packages/google-compute-engine-oslogin/pam_module/pam_oslogin_admin.cc
Labels: cla: yes, ok-to-test, size/XS

#794 New package versioning
  daisy_workflows/build_deb_packages.sh
  daisy_workflows/build_debian.wf.json
  packages/gce-disk-expand/packaging/debian/changelog
  packages/gce-disk-expand/packaging/gce-disk-expand.spec
  packages/gce-disk-expand/packaging/setup_deb.sh
  packages/gce-disk-expand/packaging/setup_rpm.sh
  packages/google-compute-engine-oslogin/packaging/debian/changelog
  packages/google-compute-engine-oslogin/packaging/google-compute-engine-oslogin.spec
  packages/google-compute-engine-oslogin/packaging/setup_deb.sh
  packages/google-compute-engine-oslogin/packaging/setup_rpm.sh
  packages/google-compute-engine-oslogin/src/Makefile
  packages/google-compute-engine/packaging/debian/changelog
  packages/google-compute-engine/packaging/debian/control
  packages/google-compute-engine/packaging/google-compute-engine-el6.spec
  packages/google-compute-engine/packaging/google-compute-engine.spec
  packages/google-compute-engine/packaging/setup_deb.sh
  packages/google-compute-engine/packaging/setup_rpm.sh
  packages/python-google-compute-engine/packaging/debian/changelog
  packages/python-google-compute-engine/packaging/python-google-compute-engine.spec
  packages/python-google-compute-engine/packaging/python3-google-compute-engine.spec
  packages/python-google-compute-engine/packaging/setup_deb.sh
  packages/python-google-compute-engine/packaging/setup_rpm.sh
  packages/python-google-compute-engine/setup.py
Labels: cla: yes, size/L

#803 Fix gce_disk_expand for Debian.
  daisy_workflows/build_debian.wf.json
  packages/gce-disk-expand/packaging/debian/control
  packages/gce-disk-expand/packaging/debian/install
  packages/gce-disk-expand/src/usr/share/initramfs-tools/hooks/expand-rootfs
  packages/gce-disk-expand/src/usr/share/initramfs-tools/scripts/local-premount/expand_rootfs
Labels: cla: yes, size/M

#784 Groups
  packages/google-compute-engine-oslogin/src/include/oslogin_utils.h
  packages/google-compute-engine-oslogin/src/nss/nss_oslogin.cc
  packages/google-compute-engine-oslogin/src/utils.cc
  packages/google-compute-engine-oslogin/test/oslogin_utils_test.cc
Labels: cla: yes, size/XL

#804 Update README's.
  README.md
  packages/gce-disk-expand/README.md
Labels: cla: yes, size/M

#807 Fix syslog output for metadata scripts for systemd.
  packages/google-compute-engine/src/lib/systemd/system/google-instance-setup.service
  packages/google-compute-engine/src/lib/systemd/system/google-shutdown-scripts.service
  packages/google-compute-engine/src/lib/systemd/system/google-startup-scripts.service
Labels: cla: yes, size/XS

#808 Specify cpp version in Makefile
  packages/google-compute-engine-oslogin/src/Makefile
Labels: cla: yes, size/S

#790 Support for Google Private Access over IPv6
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_8/tests/utils_test.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_8/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_9/tests/utils_test.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_9/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/el_6/tests/utils_test.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/el_6/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/el_7/tests/utils_test.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/el_7/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/helpers.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/tests/helpers_test.py
  packages/python-google-compute-engine/google_compute_engine/networking/network_daemon.py
  packages/python-google-compute-engine/google_compute_engine/networking/network_setup/network_setup.py
  packages/python-google-compute-engine/google_compute_engine/networking/network_setup/tests/network_setup_test.py
  packages/python-google-compute-engine/google_compute_engine/networking/tests/network_daemon_test.py
Labels: cla: yes, size/L

#809 Fixbuild
  packages/google-compute-engine-oslogin/src/Makefile
  packages/google-compute-engine-oslogin/src/include/oslogin_utils.h
  packages/google-compute-engine-oslogin/src/nss/nss_oslogin.cc
  packages/google-compute-engine-oslogin/src/utils.cc
Labels: cla: yes, size/S

#810 Switch to the v1 Guest Attributes URL.
  packages/python-google-compute-engine/google_compute_engine/instance_setup/instance_setup.py
  packages/python-google-compute-engine/google_compute_engine/instance_setup/tests/instance_setup_test.py
Labels: cla: yes, size/XS

#812 Remove unused binary search logic
  packages/google-compute-engine-oslogin/src/nss/nss_cache_oslogin.c
Labels: cla: yes, size/L

#816 Prepare for release. Bump versions.
  packages/google-compute-engine-oslogin/packaging/debian/changelog
  packages/google-compute-engine-oslogin/packaging/setup_deb.sh
  packages/google-compute-engine-oslogin/packaging/setup_rpm.sh
  packages/google-compute-engine-oslogin/src/Makefile
  packages/google-compute-engine/packaging/debian/changelog
  packages/google-compute-engine/packaging/setup_deb.sh
  packages/google-compute-engine/packaging/setup_rpm.sh
  packages/python-google-compute-engine/packaging/debian/changelog
  packages/python-google-compute-engine/packaging/setup_deb.sh
  packages/python-google-compute-engine/packaging/setup_rpm.sh
  packages/python-google-compute-engine/setup.py
Labels: cla: yes, size/M

#821 Correct JSON refcount decrementing
  packages/google-compute-engine-oslogin/src/utils.cc
Labels: cla: yes, size/XS

#822 Update script retrieval for Python 2 and 3.
  packages/python-google-compute-engine/google_compute_engine/metadata_scripts/script_retriever.py
  packages/python-google-compute-engine/google_compute_engine/metadata_scripts/tests/script_retriever_test.py
Labels: cla: yes, size/XS
