Repository GoogleCloudPlatform/compute-image-packages, pull requests merged in 2019-11, with the labels that each got.

#864 Added retry loop to _HandleMetadataUpdate
  packages/python-google-compute-engine/google_compute_engine/metadata_watcher.py
  packages/python-google-compute-engine/google_compute_engine/tests/metadata_watcher_test.py
Labels: cla: yes, lgtm, size/M

#865 Disable overcommit accounting on E2 VMs
  packages/python-google-compute-engine/google_compute_engine/instance_setup/instance_setup.py
  packages/python-google-compute-engine/google_compute_engine/instance_setup/tests/instance_setup_test.py
Labels: cla: yes, size/S

#861 Wait on tentative v6 link-local addrs before DHCP
  packages/python-google-compute-engine/google_compute_engine/distro_lib/helpers.py
Labels: cla: yes, lgtm, size/S

#866 Version:20191112.0
  packages/google-compute-engine/packaging/debian/changelog
  packages/google-compute-engine/packaging/google-compute-engine-el6.spec
  packages/google-compute-engine/packaging/google-compute-engine.spec
  packages/python-google-compute-engine/packaging/debian/changelog
  packages/python-google-compute-engine/packaging/setup_deb.sh
  packages/python-google-compute-engine/packaging/setup_rpm.sh
  packages/python-google-compute-engine/setup.py
Labels: cla: yes, size/M

#868 Add a missed change for retries
  packages/python-google-compute-engine/google_compute_engine/metadata_scripts/script_retriever.py
  packages/python-google-compute-engine/google_compute_engine/metadata_scripts/tests/script_retriever_test.py
Labels: cla: yes, lgtm, size/XS

#867 Fix typo and package build.
  daisy_workflows/build_deb_packages.sh
  packages/google-compute-engine/packaging/debian/changelog
Labels: cla: yes, size/XS

#871 Revert "Disable overcommit accounting on E2 VMs (#865)"
  packages/python-google-compute-engine/google_compute_engine/instance_setup/instance_setup.py
  packages/python-google-compute-engine/google_compute_engine/instance_setup/tests/instance_setup_test.py
Labels: cla: yes, lgtm, size/S

#872 Roll versions forward for #871
  packages/python-google-compute-engine/packaging/debian/changelog
  packages/python-google-compute-engine/packaging/setup_deb.sh
  packages/python-google-compute-engine/packaging/setup_rpm.sh
Labels: cla: yes, lgtm, size/S

#875 Revert #864, #868
  packages/python-google-compute-engine/google_compute_engine/metadata_scripts/script_retriever.py
  packages/python-google-compute-engine/google_compute_engine/metadata_scripts/tests/script_retriever_test.py
  packages/python-google-compute-engine/google_compute_engine/metadata_watcher.py
  packages/python-google-compute-engine/google_compute_engine/tests/metadata_watcher_test.py
Labels: cla: yes, lgtm, size/M

#874 Disable overcommit accounting on E2 VMs (again)
  packages/python-google-compute-engine/google_compute_engine/instance_setup/instance_setup.py
  packages/python-google-compute-engine/google_compute_engine/instance_setup/tests/instance_setup_test.py
Labels: cla: yes, lgtm, size/M

#877 version bump for revert
  packages/python-google-compute-engine/packaging/debian/changelog
  packages/python-google-compute-engine/packaging/setup_deb.sh
  packages/python-google-compute-engine/packaging/setup_rpm.sh
Labels: cla: yes, lgtm, size/S
