Repository GoogleCloudPlatform/compute-image-packages, pull requests merged in 2019-08, with the labels that each got.

#823 Re-enable boto config and don't write plugin line.
  packages/python-google-compute-engine/google_compute_engine/boto/boto_config.py
  packages/python-google-compute-engine/google_compute_engine/boto/tests/boto_config_test.py
  packages/python-google-compute-engine/google_compute_engine/constants.py
  packages/python-google-compute-engine/google_compute_engine/instance_setup/instance_config.py
Labels: cla: yes, size/S

#825 Bump versions.
  packages/google-compute-engine-oslogin/packaging/debian/changelog
  packages/google-compute-engine-oslogin/packaging/setup_deb.sh
  packages/google-compute-engine-oslogin/packaging/setup_rpm.sh
  packages/google-compute-engine-oslogin/src/Makefile
  packages/google-compute-engine/packaging/debian/changelog
  packages/google-compute-engine/packaging/setup_deb.sh
  packages/google-compute-engine/packaging/setup_rpm.sh
  packages/python-google-compute-engine/packaging/debian/changelog
  packages/python-google-compute-engine/packaging/setup_deb.sh
  packages/python-google-compute-engine/packaging/setup_rpm.sh
  packages/python-google-compute-engine/setup.py
Labels: cla: yes, size/M

#826 Add msg to consult gsutil team before changing cfg
  packages/python-google-compute-engine/google_compute_engine/boto/boto_config.py
  packages/python-google-compute-engine/google_compute_engine/instance_setup/instance_config.py
Labels: cla: yes, size/XS

#832 Fix python setup.py version to be complaint with legacy builds.
  packages/python-google-compute-engine/setup.py
Labels: cla: yes, size/XS

#833 Move oslogin to new repo
  daisy_workflows/build_deb_packages.sh
  daisy_workflows/build_el_packages.sh
  packages/google-compute-engine-oslogin/Makefile
  packages/google-compute-engine-oslogin/README.md
  packages/google-compute-engine-oslogin/google_oslogin_control
  packages/google-compute-engine-oslogin/man/nss-cache-oslogin.8
  packages/google-compute-engine-oslogin/man/nss-oslogin.8
  packages/google-compute-engine-oslogin/packaging/debian/changelog
  packages/google-compute-engine-oslogin/packaging/debian/compat
  packages/google-compute-engine-oslogin/packaging/debian/control
  packages/google-compute-engine-oslogin/packaging/debian/copyright
  packages/google-compute-engine-oslogin/packaging/debian/rules
  packages/google-compute-engine-oslogin/packaging/debian/source/format
  packages/google-compute-engine-oslogin/packaging/google-compute-engine-oslogin.spec
  packages/google-compute-engine-oslogin/packaging/setup_deb.sh
  packages/google-compute-engine-oslogin/packaging/setup_rpm.sh
  packages/google-compute-engine-oslogin/selinux/Makefile
  packages/google-compute-engine-oslogin/selinux/README.md
  packages/google-compute-engine-oslogin/selinux/oslogin.fc
  packages/google-compute-engine-oslogin/selinux/oslogin.pp
  packages/google-compute-engine-oslogin/selinux/oslogin.te
  packages/google-compute-engine-oslogin/src/Makefile
  packages/google-compute-engine-oslogin/src/authorized_keys/authorized_keys.cc
  packages/google-compute-engine-oslogin/src/cache_refresh/cache_refresh.cc
  packages/google-compute-engine-oslogin/src/include/compat.h
  packages/google-compute-engine-oslogin/src/include/nss_cache_oslogin.h
  packages/google-compute-engine-oslogin/src/include/oslogin_utils.h
  packages/google-compute-engine-oslogin/src/nss/compat/getpwent_r.c
  packages/google-compute-engine-oslogin/src/nss/nss_cache_oslogin.c
  packages/google-compute-engine-oslogin/src/nss/nss_oslogin.cc
  packages/google-compute-engine-oslogin/src/pam/pam_oslogin_admin.cc
  packages/google-compute-engine-oslogin/src/pam/pam_oslogin_login.cc
  packages/google-compute-engine-oslogin/src/utils.cc
  packages/google-compute-engine-oslogin/test/Makefile
  packages/google-compute-engine-oslogin/test/oslogin_utils_test.cc
Labels: cla: yes, size/XXL

#835 Detect hostname changes
  packages/python-google-compute-engine/google_compute_engine/compat.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_8/__init__.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_8/tests/__init__.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_8/tests/utils_test.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_8/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_9/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/el_6/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/el_7/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/freebsd_11/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/helpers.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/sles_11/__init__.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/sles_11/tests/__init__.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/sles_11/tests/utils_test.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/sles_11/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/sles_12/utils.py
  packages/python-google-compute-engine/google_compute_engine/networking/network_daemon.py
  packages/python-google-compute-engine/google_compute_engine/networking/tests/network_daemon_test.py
  packages/python-google-compute-engine/google_compute_engine/tests/compat_test.py
Labels: cla: yes, size/L

#828 Use non-numeric project ID in generated boto.cfg for GSUtil
  packages/python-google-compute-engine/google_compute_engine/boto/boto_config.py
  packages/python-google-compute-engine/google_compute_engine/boto/tests/boto_config_test.py
Labels: cla: yes, size/S
