Repository GoogleCloudPlatform/compute-image-packages, pull requests merged in 2019-06, with the labels that each got.

#786 Add manpages for NSS modules
  packages/google-compute-engine-oslogin/nss_module/nss-cache-oslogin.8
  packages/google-compute-engine-oslogin/nss_module/nss-oslogin.8
  packages/google-compute-engine-oslogin/packaging/debian/changelog
  packages/google-compute-engine-oslogin/packaging/debian/links
  packages/google-compute-engine-oslogin/packaging/debian/manpages
Labels: cla: yes

#787 Refactor Makefile
  packages/google-compute-engine-oslogin/Makefile
  packages/google-compute-engine-oslogin/nss_module/compat/getpwent_r.c
  packages/google-compute-engine-oslogin/nss_module/nss_cache_oslogin.c
  packages/google-compute-engine-oslogin/nss_module/nss_cache_oslogin.h
  packages/google-compute-engine-oslogin/packaging/debian/links
  packages/google-compute-engine-oslogin/packaging/debian/manpages
  packages/google-compute-engine-oslogin/packaging/debian/rules
  packages/google-compute-engine-oslogin/packaging/google-compute-engine-oslogin.spec
  packages/google-compute-engine-oslogin/packaging/setup_deb.sh
Labels: cla: yes

#792 Build deb9/deb10 versions for gce-oslogin
  packages/google-compute-engine-oslogin/packaging/setup_deb.sh
Labels: cla: yes, size/S

#788 Dir refactor
  packages/google-compute-engine-oslogin/Makefile
  packages/google-compute-engine-oslogin/README.md
  packages/google-compute-engine-oslogin/google_oslogin_control
  packages/google-compute-engine-oslogin/man/nss-cache-oslogin.8
  packages/google-compute-engine-oslogin/man/nss-oslogin.8
  packages/google-compute-engine-oslogin/selinux/Makefile
  packages/google-compute-engine-oslogin/selinux/README.md
  packages/google-compute-engine-oslogin/selinux/oslogin.fc
  packages/google-compute-engine-oslogin/selinux/oslogin.pp
  packages/google-compute-engine-oslogin/selinux/oslogin.te
  packages/google-compute-engine-oslogin/src/Makefile
  packages/google-compute-engine-oslogin/src/authorized_keys/authorized_keys.cc
  packages/google-compute-engine-oslogin/src/cache_refresh/cache_refresh.cc
  packages/google-compute-engine-oslogin/src/include/compat.h
  packages/google-compute-engine-oslogin/src/include/nss_cache_oslogin.h
  packages/google-compute-engine-oslogin/src/include/oslogin_utils.h
  packages/google-compute-engine-oslogin/src/nss/compat/getpwent_r.c
  packages/google-compute-engine-oslogin/src/nss/nss_cache_oslogin.c
  packages/google-compute-engine-oslogin/src/nss/nss_oslogin.cc
  packages/google-compute-engine-oslogin/src/pam/pam_oslogin_admin.cc
  packages/google-compute-engine-oslogin/src/pam/pam_oslogin_login.cc
  packages/google-compute-engine-oslogin/src/utils.cc
  packages/google-compute-engine-oslogin/test/Makefile
  packages/google-compute-engine-oslogin/test/oslogin_utils_test.cc
  packages/google-compute-engine-oslogin/utils/run_tests.sh
Labels: cla: yes, size/L

#791 Cleanup build files pull in distro patches.
  packages/google-compute-engine/packaging/debian/changelog
  packages/google-compute-engine/packaging/debian/compat
  packages/google-compute-engine/packaging/debian/control
  packages/google-compute-engine/packaging/debian/google-compute-engine.links
  packages/google-compute-engine/packaging/debian/install
  packages/google-compute-engine/packaging/debian/rules
  packages/google-compute-engine/packaging/google-compute-engine-el6.spec
  packages/google-compute-engine/src/etc/dhcp/dhclient-exit-hooks
  packages/google-compute-engine/src/etc/dhcp/dhclient-exit-hooks.d/google_set_hostname
  packages/google-compute-engine/src/lib/systemd/system/google-accounts-daemon.service
  packages/google-compute-engine/src/lib/systemd/system/google-clock-skew-daemon.service
  packages/google-compute-engine/src/lib/systemd/system/google-instance-setup.service
  packages/google-compute-engine/src/lib/systemd/system/google-network-daemon.service
  packages/google-compute-engine/src/lib/systemd/system/google-shutdown-scripts.service
  packages/google-compute-engine/src/lib/systemd/system/google-startup-scripts.service
  packages/google-compute-engine/src/usr/lib/systemd/journald.conf.d/20-google.conf
  packages/python-google-compute-engine/packaging/debian/changelog
  packages/python-google-compute-engine/packaging/debian/compat
  packages/python-google-compute-engine/packaging/debian/control
  packages/python-google-compute-engine/packaging/debian/rules
  packages/python-google-compute-engine/packaging/setup_deb.sh
Labels: cla: yes, size/M

#795 Fix debian python3 dependencies.
  packages/python-google-compute-engine/packaging/debian/control
Labels: cla: yes, size/S

#798 Disk expand: fixes for GPT
  packages/gce-disk-expand/packaging/gce-disk-expand.spec
  packages/gce-disk-expand/packaging/setup_rpm.sh
  packages/gce-disk-expand/src/expandfs-lib.sh
  packages/gce-disk-expand/src/usr/share/dracut/modules.d/50expand_rootfs/expand_rootfs.sh
  packages/gce-disk-expand/src/usr/share/dracut/modules.d/50expand_rootfs/xfs_growfs.sh
Labels: cla: yes, size/L

#796 google_oslogin_control: make it FreeBSD compatible
  packages/google-compute-engine-oslogin/google_oslogin_control
Labels: cla: yes, ok-to-test, size/S

#632 Enable IPv6 on interfaces based on metadata key.
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_8/tests/utils_test.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_8/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_9/tests/utils_test.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_9/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/el_6/tests/utils_test.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/el_6/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/el_7/tests/utils_test.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/el_7/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/freebsd_11/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/helpers.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/sles_11/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/sles_12/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/tests/helpers_test.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/utils.py
  packages/python-google-compute-engine/google_compute_engine/networking/network_daemon.py
  packages/python-google-compute-engine/google_compute_engine/networking/network_setup/network_setup.py
  packages/python-google-compute-engine/google_compute_engine/networking/network_setup/tests/network_setup_test.py
  packages/python-google-compute-engine/google_compute_engine/networking/tests/network_daemon_test.py
Labels: cla: yes, size/L
