Repository GoogleCloudPlatform/compute-image-packages, pull requests merged in 2019-09, with the labels that each got.

#842 Bump versions to 20190905
  packages/google-compute-engine/packaging/debian/changelog
  packages/google-compute-engine/packaging/setup_deb.sh
  packages/google-compute-engine/packaging/setup_rpm.sh
  packages/python-google-compute-engine/packaging/debian/changelog
  packages/python-google-compute-engine/packaging/setup_deb.sh
  packages/python-google-compute-engine/packaging/setup_rpm.sh
Labels: cla: yes, size/S

#843 remove deb10 builds
  daisy_workflows/build_deb_packages.sh
  daisy_workflows/build_debian.wf.json
  packages/python-google-compute-engine/setup.py
Labels: cla: yes, size/M

#846 Add missing DisableIpv6 function for SLES 12 and default case.
  packages/python-google-compute-engine/google_compute_engine/distro_lib/sles_12/utils.py
  packages/python-google-compute-engine/google_compute_engine/distro_lib/utils.py
Labels: cla: yes, lgtm, size/S

#841 run startup scripts before apt-daily
  packages/google-compute-engine/src/lib/systemd/system/google-startup-scripts.service
Labels: cla: yes, size/XS

#847 fix network restart loop
  packages/python-google-compute-engine/google_compute_engine/networking/network_daemon.py
Labels: cla: yes, lgtm, size/XS

#850 Rollback VM rename
  packages/python-google-compute-engine/google_compute_engine/networking/network_daemon.py
  packages/python-google-compute-engine/google_compute_engine/networking/tests/network_daemon_test.py
Labels: cla: yes, lgtm, size/M

#848 Fix EL6 spec to not call systemctl and put that logic back in the EL7+
  packages/google-compute-engine/packaging/google-compute-engine-el6.spec
  packages/google-compute-engine/packaging/google-compute-engine.spec
Labels: cla: yes, lgtm, size/S

#851 Bump versions.
  packages/google-compute-engine/packaging/debian/changelog
  packages/google-compute-engine/packaging/setup_deb.sh
  packages/google-compute-engine/packaging/setup_rpm.sh
  packages/python-google-compute-engine/packaging/debian/changelog
  packages/python-google-compute-engine/packaging/setup_deb.sh
  packages/python-google-compute-engine/packaging/setup_rpm.sh
  packages/python-google-compute-engine/setup.py
Labels: cla: yes, size/S
